const hotels = [
    {
      id: '1',
      name: 'RCC Pristine',
      location: 'Ameerpet',
      price: 1200,
      image: 'https://rcchotels.com/wp-content/uploads/2021/09/best-rcc-elite-begumpet-605x465.jpeg',
      rating:5.0,
      details: `RCC Pristine in Ameerpet is a budget luxury hotel located in Ameerpet, Hyderabad. The hotel offers comfortable stays at affordable prices, and exceeds guest expectations with every stay. It’s conveniently located 10 km from the Charminar, 9 km from Golconda Fort, and close to other major attractions like the Salar Jung Museum. The hotel also offer parking facility, dining area, CCTV Cameras`,
    },
    {
      id: '2',
      name: 'RCC ELITE',
      location: 'Begumpet',
      price: 1700,
      rating:4.5,
      image: 'https://rcchotels.com/wp-content/uploads/2021/09/top-hotels-rcc-elite-begumpet-605x465.jpeg',
      details: `RCC Elite is a perfect place to stay in Hyderabad. The hotel offers a good location as it is just 9 km from Charminar and 10 km from Golconda Fort. It provides an In-house restaurant, Kitchen, Dining Area for its guests to enjoy their time here`,
    },
    {
      id: '3',
      name: 'RCC Sunrise',
      location: 'Begumpet',
      price: 1900,
      rating:5.0,
      image: 'https://rcchotels.com/wp-content/uploads/2021/09/luxury-hotels-rcc-elite-begumpet-605x465.jpeg',
      details: `Located in the Begumpet area in Secunderabad, the property is 20 mins away from the famous Jubilee Hills. Celebrity Club Park and DoScience Museum are within 15min drive from the hotel. Golconda Fort and the iconic Charminar are couple of kms away and can be covered easily from this property.`,
    },
    {
      id: '4',
      name: 'RCC Majestic',
      location: 'LB Nagar',
      price: 1000,
      rating:4.5,
      image: 'https://rcchotels.com/wp-content/uploads/2021/07/luxury-hotels-in-hyderabad-605x459.jpg',
      details: `With a prime location in Hyderabad, this hotel is perfect for both business and leisure travelers. The top attractions are 6 km from Charminar and 14 km from Golconda Fort. It has a parking facility, an in-house restaurant and CCTV Cameras for enhanced security`,
    },
    {
      id: '5',
      name: 'RCC Prime',
      location: 'Moosapet',
      price: 1000,
      rating:5,
      image: 'https://rcchotels.com/wp-content/uploads/2021/07/luxury-hotels-in-hyderabad-605x459.jpg',
      details: `Located in SP Nagar, Moosapet, Hyderabad, the property is a restful and chic stay choice at an affordable price. Tourist attractions located close to the place that the guests can visit during their stay include the Shilparamam, the Qutub Shahi Tombs, the Golconda Fort, Shri Jagannath Temple, and Emaar MGF Boulder Hills`,
    },
    {
      id: '6',
      name: 'RCC Blizz',
      location: 'Kondapur',
      price: 1000,
      rating:4.8,
      image: 'https://rcchotels.com/wp-content/uploads/2021/07/luxury-hotels-in-hyderabad-605x459.jpg',
      details: `Sanitized Rooms with King Sized bed, TV, AC, Room Service, 24/7 Security.`,
    },
    {
      id: '7',
      name: 'RCC ParkViewInn',
      location: 'Miyapur',
      price: 1000,
      rating:5,
      image: 'https://rcchotels.com/wp-content/uploads/2021/07/luxury-hotels-in-hyderabad-605x459.jpg',
      details: `Sanitized Rooms with King Sized bed, TV, AC, Room Service, 24/7 Security.`,
    },
    {
      id: '8',
      name: 'RCC Pride',
      location: 'Kukatpally',
      price: 1000,
      rating:5,
      image: 'https://rcchotels.com/wp-content/uploads/2021/07/luxury-hotels-in-hyderabad-605x459.jpg',
      details: `Located in Kukatpally the property is a restful and luxury stay choice at an affordable price. Tourist attractions located close to the place that the guests can visit during their stay include the Mahalakshmi Venkateshwara Temple, Medak Church, Taramati Baradari, Medak Fort, Kulpakji Jain Mandir etc`,
    },
  ];
  
  export default hotels;